from .login import route_login
from .emprestimo import route_emp
from .home import route_home
from .devolver import route_dev
from .adicionar import route_add
from .down import route_down
from .logout import route_logout
from .troca_de_senha import route_pass
from .novo_usuario import route_new_user
